version: '3'

services:
  postgres:
    image: postgres:15.4
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
     - postgres-volume:/var/lib/postgresql/data
     - ./init/looper.sql:/docker-entrypoint-initdb.d/looper.sql
    restart: on-failure
    ports:
      - "5432:5432"

volumes:
  postgres-volume:
