[default]
address = "127.0.0.1"
port = 8000
max_blocking = 512
ident = "Rocket"
log_level = "normal"

[default.limits]
form = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"
timeout = 55

[default.shutdown]
ctrlc = true
signals = ["term", "hup"]
grace = 5
mercy = 5
