name: Lint

on:
  - workflow_call

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/looper_test
  PROFILE: test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Rust Cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/ 
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-looper-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-looper-

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Format
      run: cargo fmt --all -- --check

    - name: Clippy
      run: cargo clippy --verbose -- -D warnings
    # - name: Audit
    #   run: cargo audit
